services:
  db:
    image: postgres:16
    restart: always
    ports: 
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=raw


    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 30s
      retries: 5

  extractor:
    build: ETL
    restart: on-failure
    depends_on:
      db:
        condition: service_healthy

networks:
  covidnet:
    driver: bridge
