services:
  db:
    image: postgres:16
    restart: always
    shm_size: 128mb
    ports: 
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: naartjie
      POSTGRES_USER: etl_user
      POSTGRES_DB: raw
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 30s
      retries: 5

  extractor:
    build: ETL
    depends_on:
      db:
        condition: service_healthy

    environment:
      - DATABASE_HOST=db:5432

